### ISSUE TITLE
did you use any UI kits here?

### ISSUE THREAD

**Issue by atherdon** [guruduttperi/Meal_Planning_UX#1]

**Comment by guruduttperi** [comment]
Yes, I've used a few icon sets. 
Here are links to the resources:
https://www.sketchappsources.com/free-source/3230-hephestos-misc-icons-sketch-freebie-resource.html
https://www.sketchappsources.com/free-source/3034-feather-sketch-library-freebie-resource.html
https://www.sketchappsources.com/free-source/1938-stars-rating-template-sketch-freebie-resource.html

**Comment by atherdon** [comment]
we'll put that links into credits
