### ISSUE TITLE
can you upload sketch file here too?

### ISSUE THREAD

**Issue by atherdon** [guruduttperi/Meal_Planning_UX#3]

**Comment by guruduttperi** [comment]
I can't upload it here since the file is pretty large. 
I've linked it up on Google Drive: https://drive.google.com/open?id=17Ca-jcbkWvnOBCqUJwSgGgffTcS0-PRb

**Comment by atherdon** [comment]
thanks

**Comment by atherdon** [comment]
do you want to add that screens to your angellist profile like a project? also did you plan to post it on dribble? curious to see what their members will tell

**Comment by guruduttperi** [comment]
I was planning to post it on Behance like a case study. I'll have to work on it a little bit.

**Comment by atherdon** [comment]
for sure. i like plan to post on Behance


On 27-May-2018 at 01:32 PM, Gurudutt Perichetla wrote:


I was planning to post it on Behance like a case study. I'll have to work
on it a little bit.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/guruduttperi/Meal_Planning_UX/issues/3#issuecomment-392331342>,
or mute the thread

**Comment by guruduttperi** [comment]
Here's the Behance Link: https://www.behance.net/gallery/66090061/Groceristar-Meal-Planning-UX?

**Comment by guruduttperi** [comment]
Dribbble:
https://dribbble.com/shots/4637526-Meal-Planning-UX-Login
https://dribbble.com/shots/4637527-Meal-Planning-UX-Your-Meals

**Comment by atherdon** [comment]
yep, i find it. looks awesome!


On 27-May-2018 at 02:19 PM, Gurudutt Perichetla wrote:


Here's the Behance Link:
https://www.behance.net/gallery/66090061/Groceristar-Meal-Planning-UX?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/guruduttperi/Meal_Planning_UX/issues/3#issuecomment-392334355>,
or mute the thread

**Comment by atherdon** [comment]
please move this links to readme, so we can close this task

**Comment by guruduttperi** [comment]
Done!
