### ISSUE TITLE
notes

### ISSUE THREAD

**Issue by atherdon** [guruduttperi/Meal_Planning_UX#4]
Let's chat about FB login button. -> Maybe it should be in FB color scheme?

Not sure about Form at header.
I like it because it's easy to sign in.

But another is put just a 2 links - Sign Up Sign In - as a lot of startups did.
But this is debatable.

Important thing is related to recipes personalization of current user.

I mean by default - user should fill a long and stupid form with fields like allergies, etc.

I think we should have something more great. it'll give us more options to compete with other similar services.

**Comment by guruduttperi** [comment]
I think we can have a screen for the form to collect user details - all his allergies and other fields.
Using that, I think we can personalize the recipes. I have an idea - about Vegan, Vegetarian, Pescatarian and Non-Vegetarian types - so we can categorize or classify users to help suggest those recipes to the different types of people.

**Comment by atherdon** [comment]
i agree with your idea. but it shoudn't be just a form. i mean - form
sucks :) so if can show me some cool way, how we can avoid this confusing
way - it'll be perfect!
