### ISSUE TITLE
notes #2

### ISSUE THREAD

**Issue by atherdon** [guruduttperi/Meal_Planning_UX#5]
1) I think we should create design for meal calendar page. we have a button, but how it'll looks when you click on it?
2) i think we should create weekly menu page. i can show you a sample from app that wi did before
3) i think we should create a Grocery List page too. Curious about what you can do with it :) have samples - can share upon request too

**Comment by guruduttperi** [comment]
I am currently working on these pages - will update soon.

**Comment by atherdon** [comment]
perfect!


On 04-Jun-2018 at 05:27 AM, Gurudutt Perichetla wrote:


I am currently working on these pages - will update soon.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/guruduttperi/Meal_Planning_UX/issues/5#issuecomment-394238027>,
or mute the thread

**Comment by guruduttperi** [comment]
I've created a repo for the new design: https://github.com/guruduttperi/Meal_Planning_UX_Build_2

We'll close discussions on this repo - since there are some changes I've made in the workflow.

**Comment by atherdon** [comment]
will check when wake up


On 06-Jun-2018 at 06:30 AM, Gurudutt Perichetla wrote:


I've created a repo for the new design:
https://github.com/guruduttperi/Meal_Planning_UX_Build_2

We'll close discussions on this repo - since there are some changes I've
made in the workflow.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/guruduttperi/Meal_Planning_UX/issues/5#issuecomment-394955571>,
or mute the thread
